---
- name: Upload files
  copy:
    src: "{{ item }}"
    dest: /root/registry/
  with_items:
    - docker-compose.yml
    - Dockerfile.1
    - Dockerfile.2
    - Dockerfile.3
    - flag.txt
    - something.txt
    - exercises.txt
    - cheat-sheet.txt

- name: Bring up registry
  docker_compose:
    project_src: /root/registry/
    state: present

- name: Build and push images
  docker_image:
    path: /root/registry
    dockerfile: "{{ item.file }}"
    name: 127.0.0.1:5000/supersecretimage
    tag: "{{ item.version }}"
    push: yes
  with_items:
    - file: Dockerfile.1
      version: v1
    - file: Dockerfile.2
      version: v2
    - file: Dockerfile.3
      version: v3
