---
- name: update apt cache and install dependancies
  apt:
    name: [
    'apt-transport-https',
    'ca-certificates',
    'curl',
    'software-properties-common'
    ]
    update_cache: yes
    state: present

- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: register lsb release
  command: lsb_release -cs
  register: lsb_release

- name: add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

- name: install docker-ce
  apt:
    name: docker-ce

- name: Restart docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
